export const ActionTypes = {
    FETCH_PROGRAMS : "FETCH_PROGRAMS",
    FETCH_PROGRAM_BY_ID: "FETCH_PROGRAM_BY_ID",
    FETCH_COURSES: "FETCH_COURSES",
    FETCH_COURSE_BY_ID: "FETCH_COURSE_BY_ID",
    GET_MAIL_DOWNLOAD: "GET_MAIL_DOWNLOAD",
    GET_VISITORS: "GET_VISITORS",
    GET_ROLES: "GET_ROLES"
}